### PR TITLE
Update for Bioconductor 3.1 release.

### PR DESCRIPTION
**Pull request by deflaux**
@mbookman Please see the updated instructions.  The first call to `biocLite` will prompt the user to update other packages, but its not followed by any other commands so copy/paste is not interrupted.

@siddharthab Since this codelab is compatible with the version of `GoogleGenomics` in the Bioconductor 3.1 release, I just kept the install instructions simple.  I'm guessing that on https://github.com/googlegenomics/api-client-r you'll mention bioc-devel, etc...

### CODE REVIEW

**Comment by siddharthab** [comment]
LGTM. I will put instructions for devel package install in the other repo.

**Comment by mbookman** [comment]
Want to verify something.
I have R 3.1.2 installed.  When I run:

biocLite("GoogleGenomics")

I see...

Bioconductor version 3.0 (BiocInstaller 1.16.4), ?biocLite for help
A new version of Bioconductor is available after installing the most recent version of R; see
  http://bioconductor.org/install

"A new version" here means Bioconductor 3.1.  So to get Bioconductor 3.1, I need to move to R 3.2.

If someone were to be stuck on R 3.1 (perhaps they don't control their client?) is there somewhere they can go for the Google Genomics install instructions that apply to R 3.1?

**Comment by pgrosu** [comment]
@wbrockman, to be safe perform the following tests - which is what I usually do:

1. Have multiple versions of R that are clean.
2. Test on the earliest and progress to the newest.
3. Check that the tests all output the same answers.  If not, then adjust the minimum version requirement to the package that ensures equality among the tests.

~p

**Comment by deflaux** [comment]
Good question.  The answer is "not currently".  If we want to cover that case, its restoring the `devtools` install instructions.  We could leave them somewhere (e.g. on api-client-r) and link to them for those that cannot upgrade.

But I think the right answer going forward for those situations is to virtualize: http://master.bioconductor.org/help/docker/ 

Its next on my list to incorporate the Docker instructions.

**Pull request merged**
