### PR TITLE
Update homozygous-variants.sql.

### PR DESCRIPTION
**Pull request by arostamianfar**
@deflaux 
Bug fixes to include all variants (i.e. SNPs and indels) and exclude records where all samples have the same allele. These modifications were performed after analyzing VCFtools' method.

### CODE REVIEW

**Comment by arostamianfar** [comment]
Signed the CLA.

**Comment by deflaux** [comment]
@arostamianfar apologies on the delay for the review of this

After further thought, I think we need to put back in the logic that restricts this query to SNPs only.  The reason is that the "expanded table" only expands non-variant segments onto SNPs (see https://github.com/googlegenomics/codelabs/tree/master/Java/PlatinumGenomes-variant-transformation).  This means that for indels, the nested records _only_ have the variant (none match the reference), so the allelic frequency would be incorrect.

Perhaps add a comment to that effect explaining why it needs to be SNPs only?  (And clearly, that comment should have already been in there.) 

Thank you!

**Comment by arostamianfar** [comment]
ah...I did not realize that's the case! Nice catch! Updated the query with comments. PTAL.

**Comment by deflaux** [comment]
Thank you @arostamianfar !

**Pull request merged**
