### PR TITLE
Set suppressUpdate=TRUE in biocLite() calls

### PR DESCRIPTION
**Pull request by mbookman**
Makes the command block copy/paste-able.

### CODE REVIEW

**Comment by deflaux** [comment]
Good update - thank you!

Note that since the change is only in the *.md file, it will get overwritten the next time someone renders the *.Rmd file.  The Rmd is the authoritative code.

So please either:
* Change the *.Rmd file and re-render the *.md (in general, this is best)
* Or make the same change in both files.  (this is okay for certain minor changes like this or edits to the narrative)

**Comment by mbookman** [comment]
Where is the .Rmd file?

**Comment by deflaux** [comment]
Oh apologies, I mistakenly thought your were editing https://github.com/googlegenomics/codelabs/blob/master/R/1000Genomes-BRCA1-analysis/AllModalitiesDemo.md#zooming-in-even-further

**Comment by pgrosu** [comment]
Just something to be aware of, setting `suppressUpdates` to `TRUE` will not be relevant if someone installs the packages at a later version than what the `api-client-r` was built for.  I understand that for the annotations, but `ggbio` will not remain unchanged over time.

Paul

**Comment by deflaux** [comment]
Good to know, thank you @pgrosu

**Pull request merged**
